const r = (name, mins, cost, serves, ingredients, steps, tip) => ({
  name,
  mins,
  cost,
  serves,
  ingredients,
  steps,
  tip,
});

const BREAKFAST = [
  r(
    "Masala poha",
    15,
    "₹25",
    1,
    ["1.5 cups flattened rice", "1 onion", "1 potato or leftover sabzi", "mustard, curry leaf, turmeric", "lemon, salt, oil"],
    [
      "Put the poha in a wide sieve and rinse under cold water until the flakes soften and lose their chalky look. Drain well and leave it for four minutes so leftover water is absorbed, not sitting in a puddle.",
      "Heat a tablespoon of oil in a kadhai on medium. When it shimmers, add a pinch of mustard seeds. When they pop, add a few curry leaves and the chopped onion. Stir until the onion turns translucent and sweet, about three minutes.",
      "Add the diced potato or leftover sabzi and a pinch of turmeric. Cook until the potato is tender if it is raw, or just hot if it is leftover. Sprinkle salt on the vegetables now so it seasons them, not only the poha.",
      "Tip the drained poha in. Fold gently with a flat spoon so the flakes stay whole. Cover the kadhai for two minutes on a low flame so steam finishes the middle.",
      "Squeeze half a lemon over the top, taste, and add salt if the poha still tastes flat. Serve at once; masala poha goes dull if it sits covered.",
    ],
    "Buy the thick poha; thin poha turns to paste.",
  ),
  r(
    "Vegetable upma",
    18,
    "₹20",
    1,
    ["1/2 cup rava", "1/2 onion", "carrot or peas", "mustard, green chilli", "1.25 cups water"],
    [
      "Set a dry kadhai on medium heat and add the rava. Stir without oil until it smells nutty and looks a shade darker, three to four minutes. Tip it into a plate so it does not keep toasting.",
      "In the same kadhai heat a teaspoon of oil. Add mustard seeds, a slit green chilli, and the chopped onion. When the onion softens, add diced carrot or a handful of peas and cook one minute.",
      "Pour in 1.25 cups of hot water and a pinch of salt. Bring it to a lively simmer so the rava will not form lumps when it hits cold water.",
      "Rain the roasted rava in with one hand while you stir with the other. Keep stirring until it thickens into a soft mass, then cover on the lowest flame for three minutes.",
      "Fluff with a fork. If it is stiff, sprinkle a spoon of hot water, cover again for a minute, and serve with a squeeze of lemon or a spoon of curd.",
    ],
    "Leftover upma becomes next-day cutlets.",
  ),
  r(
    "Bread omelette",
    10,
    "₹30",
    1,
    ["2 eggs", "2 bread slices", "onion, chilli, coriander", "salt, oil or butter"],
    [
      "Crack the eggs into a wide bowl. Add finely chopped onion, green chilli, a pinch of salt, and a little coriander. Beat until the whites and yolks are one colour and slightly frothy.",
      "Set a tawa on medium heat and smear a thin film of oil or butter. Do not let it smoke; burnt fat makes the egg taste bitter.",
      "Dip one bread slice in the egg so both faces are coated but the slice still holds its shape. Lay it on the tawa. Repeat with the second slice, or cook one after the other if the tawa is small.",
      "Pour any leftover egg around and over the bread. After two minutes, when the underside is golden, flip and cook the second side until the egg is set and the bread is crisp at the edges.",
      "Lift onto a plate. Eat with ketchup, green chutney, or chai. Do not stack the slices or the steam will soften the crust.",
    ],
    "One pan, no mixer. Eat with ketchup or chai.",
  ),
  r(
    "Egg bhurji on toast",
    12,
    "₹30",
    1,
    ["2 eggs", "1/2 onion", "tomato optional", "2 toast slices", "turmeric, chilli"],
    [
      "Chop the onion small. If you are using tomato, chop that too and keep it ready; bhurji waits for no one once the eggs hit the pan.",
      "Heat a teaspoon of oil in a kadhai on medium-high. Fry the onion until the edges brown. Add tomato if using, a pinch of turmeric, chilli powder, and salt. Cook until the tomato softens and the raw smell goes.",
      "Beat the eggs in a cup with a fork. Pour them into the pan and leave them untouched for ten seconds so a skin forms.",
      "Then pull large soft folds from the edge to the centre. Stop when the eggs are just set and still glossy. Constant stirring makes rubber.",
      "Toast the bread while the eggs rest off the heat for half a minute. Pile the bhurji on the toast and eat at once.",
    ],
    "Do not stir constantly or it goes rubbery.",
  ),
  r(
    "Banana peanut-butter toast",
    5,
    "₹20",
    1,
    ["2 bread slices", "1 banana", "2 tsp peanut butter", "pinch of salt"],
    [
      "Toast the bread on a dry tawa or in a toaster until both sides are golden and the surface is dry enough to hold a spread.",
      "While it is still warm, spread a thin layer of peanut butter to the edges. Warm bread melts the butter so you need less of it.",
      "Slice the banana into coins. Lay them in a single layer so every bite has fruit, not a bald corner of toast.",
      "Finish with a tiny pinch of salt, or chilli flakes if you want it less like dessert. Eat before the banana browns.",
    ],
    "Add chilli flakes if you want it less dessert-like.",
  ),
  r(
    "Besan chilla",
    15,
    "₹18",
    2,
    ["1 cup besan", "water, onion, chilli", "ajwain, salt, oil"],
    [
      "Put the besan in a bowl with a pinch of ajwain and salt. Add water a little at a time, whisking until you have a pouring batter that coats the back of a spoon. Lumps now will be lumps on the tawa.",
      "Stir in finely chopped onion and green chilli. Rest the batter five minutes so the besan hydrates and the first chilla does not tear.",
      "Heat a tawa on medium. Smear a few drops of oil. Pour a ladle of batter in the centre and spread it outward in a thin circle, as you would a dosa.",
      "Cook until the top looks dry and the underside is spotted brown, two to three minutes. Flip once and cook the second side for a minute.",
      "Repeat with the rest of the batter, oiling the tawa lightly each time. Eat with pickle, chutney, or leftover sabzi rolled inside.",
    ],
    "Stuff with leftover sabzi for a wrap.",
  ),
  r(
    "Moong dal chilla",
    20,
    "₹20",
    2,
    ["1 cup soaked moong dal", "chilli, ginger", "salt, oil"],
    [
      "Soak the moong dal in plenty of water for at least four hours, or overnight. Drain. The grains should press easily between two fingers.",
      "Grind the dal with chilli, a small piece of ginger, salt, and only enough water to make a thick, spreadable batter. Too much water and the chilla will not hold.",
      "Heat a tawa on medium and grease it. Pour a ladle and spread it thinner than a pancake, thicker than a paper dosa.",
      "Drizzle a few drops of oil around the edge. When the top dries and the rim lifts, flip and cook the second side until both faces are golden.",
      "Stack them on a plate covered with a cloth so they stay soft. Eat with chutney or a spoon of curd.",
    ],
    "Soak dal overnight while you sleep.",
  ),
  r(
    "Overnight oats",
    5,
    "₹25",
    1,
    ["1/2 cup oats", "1/2 cup milk or curd", "banana or raisins", "1 tsp sugar or jaggery"],
    [
      "In a clean jar or box, mix the oats with milk or beaten curd until every flake is wet. Dry pockets stay hard in the morning.",
      "Stir in sugar or grated jaggery. Add sliced banana or a few raisins. A pinch of salt makes the sweet taste less flat.",
      "Close the lid and refrigerate at least six hours, ideally overnight. The oats will swell and turn creamy without any heat.",
      "In the morning, stir once. If it is stiff, loosen with a splash of milk. Eat cold from the jar. No gas, no pan.",
    ],
    "No gas, no morning brain.",
  ),
  r(
    "Hot milk oats",
    8,
    "₹22",
    1,
    ["1/2 cup oats", "1 cup milk", "sugar, cardamom pinch"],
    [
      "Pour the milk into a small kadhai and bring it just to a simmer on medium heat. Watch it; milk climbs the sides without warning.",
      "Add the oats and a pinch of crushed cardamom. Stir so they do not sit in a clump at the bottom.",
      "Cook five minutes, stirring now and then, until the oats are soft and the milk has thickened into a porridge.",
      "Sweeten off the heat. Taste, add a pinch of salt, and eat while it is hot. It sets as it cools.",
    ],
    "A pinch of salt makes it taste less flat.",
  ),
  r(
    "Tomato cheese sandwich",
    8,
    "₹28",
    1,
    ["4 bread slices", "1 tomato", "2 tbsp grated cheese or slice", "chaat masala, butter"],
    [
      "Slice the tomato thin and lay the slices on a plate. Sprinkle a little salt and chaat masala so the tomato is seasoned before it meets the bread.",
      "Butter one face of each bread slice. Those buttered faces will sit on the tawa and turn crisp.",
      "On the dry inner faces, layer tomato and cheese. Close the sandwiches so the butter is on the outside.",
      "Toast on a medium tawa, pressing lightly with a spatula, two to three minutes a side, until the bread is gold and the cheese has slumped.",
      "Cut diagonally and eat at once. If the tomato was very wet, the first bite will drip; that is the sandwich working.",
    ],
    "Amul slice is fine. Do not drown it.",
  ),
  r(
    "Leftover roti roll",
    8,
    "₹15",
    1,
    ["2 rotis", "egg or leftover sabzi", "onion, sauce"],
    [
      "Warm the rotis on a dry tawa for twenty seconds a side so they bend without cracking.",
      "If you are using an egg, scramble it quickly on the same tawa with a pinch of salt. If you have leftover sabzi, heat that instead until it steams.",
      "Lay the filling down the centre of each roti. Add a little chopped onion and a line of sauce or pickle oil.",
      "Roll tight and place the seam down on the tawa for a minute so it seals. Toast the outside if you want a crisp skin.",
      "Wrap the bottom in a scrap of paper or the roti packet. Eat standing if that is the morning you are having.",
    ],
    "Breakfast from last night's dinner.",
  ),
  r(
    "Boiled-egg chaat",
    12,
    "₹22",
    1,
    ["2 boiled eggs", "onion, coriander", "lemon, chilli powder, salt"],
    [
      "If the eggs are not already boiled, cover them with cold water, bring to a boil, and cook eight minutes. Cool under running water and peel.",
      "Chop the eggs into rough cubes, not mush. Put them in a bowl with finely chopped onion and coriander.",
      "Add salt, a pinch of chilli powder, and a generous squeeze of lemon. Toss with a spoon so the yolk coats the onion.",
      "Taste. It should be sharp and salty, like street chaat, not a bland salad. Eat at once; leftover egg chaat weeps in the fridge.",
    ],
    "Boil six eggs on Sunday; peel as needed.",
  ),
  r(
    "Sprouts breakfast bowl",
    10,
    "₹20",
    1,
    ["1 cup moong sprouts", "onion, tomato", "lemon, salt, jeera powder"],
    [
      "If the sprouts smell sour or look slimy, throw them away. Fresh sprouts smell clean and look plump.",
      "For a gentler plate, steam the sprouts in a covered pan with two spoons of water for three minutes. For a raw chaat, skip the steam if they are young and sweet.",
      "Tip them into a bowl. Add chopped onion, tomato, salt, a pinch of jeera powder, and lemon.",
      "Toss and taste. Add chilli powder if you want heat. Eat it as a bowl, or pile it on toast.",
    ],
    "Sprout moong in a cloth for two days.",
  ),
  r(
    "Rava idli (no moulds)",
    20,
    "₹22",
    2,
    ["1 cup roasted rava", "1/2 cup curd", "eno or fruit salt", "mustard tadka"],
    [
      "Mix the roasted rava with beaten curd and enough water to make a thick batter. Add salt. Rest ten minutes so the rava drinks the liquid.",
      "If you want a tadka, heat a little oil, pop mustard seeds, and stir that into the batter. Grease a steel tiffin box or a small bowl that fits inside your cooker.",
      "Just before steaming, stir in a pinch of eno or fruit salt. The batter should foam. Do not wait; the lift dies in minutes.",
      "Pour into the greased box. Set it on a stand in a cooker with an inch of water. Steam without the whistle weight for twelve minutes.",
      "Open, poke the centre with a knife; it should come out clean. Rest two minutes, loosen the sides, and turn out. Eat with chutney or sambar if you have it, or with pickle and oil.",
    ],
    "A cooker without whistle works as a steamer.",
  ),
  r(
    "Leftover rice dosa",
    15,
    "₹12",
    2,
    ["1 cup cooked rice", "1/4 cup atta or rava", "water, salt"],
    [
      "Put cold leftover rice in a bowl and mash it with a little water until most grains break. A few whole grains are fine; a paste is not required.",
      "Stir in atta or rava and salt. Add water until the batter is thinner than idli batter and will spread on a tawa. Rest five minutes if you used rava.",
      "Heat a tawa well. A drop of water should dance. Grease lightly. Pour a ladle and spread as thin as you can.",
      "Drizzle a few drops of oil around the edge. Cook until the underside is brown and crisp, then flip for thirty seconds if you like both sides fried.",
      "The first dosa often sticks. That is the tawa seasoning itself. The second one will behave. Eat with chutney, pickle, or a fried egg.",
    ],
    "The ugliest batter still fries well.",
  ),
  r(
    "Cornflakes banana milk",
    3,
    "₹25",
    1,
    ["1 bowl cornflakes", "milk", "1 banana"],
    [
      "Put the cornflakes in a bowl first, not the milk. Slice the banana over them so the fruit does not sink and vanish.",
      "Pour cold milk just until the flakes are wet, not swimming. You can always add more.",
      "Eat at once, from the bottom up if you must, before the flakes collapse into a sweet sludge.",
    ],
    "Keep a small box so you do not buy chips instead.",
  ),
  r(
    "Vegetable sevai",
    12,
    "₹20",
    1,
    ["1 nest rice sevai", "onion, peas", "mustard, chilli"],
    [
      "Soak the rice sevai in warm water for two minutes only. Drain in a sieve and leave it there; leftover water will turn it to glue.",
      "Heat oil in a kadhai. Pop mustard seeds, add slit chilli and chopped onion. When the onion softens, add peas and cook a minute.",
      "Add the drained sevai and salt. Toss with two forks, lifting rather than mashing, until the strands are hot and coated.",
      "Taste. A squeeze of lemon or a handful of roasted peanuts at the end makes it a meal. Serve immediately.",
    ],
    "Cheaper than Maggi; same one-pan mood.",
  ),
  r(
    "Sabudana khichdi",
    25,
    "₹30",
    1,
    ["1/2 cup soaked sabudana", "1 potato", "peanuts, cumin, chilli"],
    [
      "Rinse the sabudana, then soak it in just enough water to cover for three to four hours. The pearls should be soft all the way through when you press one. Drain any standing water.",
      "Dice a small potato small so it cooks fast. Dry-roast a handful of peanuts on a tawa, then crush them roughly.",
      "Heat a teaspoon of oil or ghee. Add cumin and slit chilli, then the potato. Cook until the potato is tender and lightly browned.",
      "Add the drained sabudana and salt. Toss on medium-low heat. The pearls should turn translucent and separate, not clump. If they stick, the soak had too much water; keep tossing on a dry tawa.",
      "Fold in the peanuts and a squeeze of lemon. Serve hot. Cold sabudana khichdi is a different, sadder dish.",
    ],
    "If pearls stick, you used too much water.",
  ),
  r(
    "Paneer bhurji toast",
    12,
    "₹40",
    1,
    ["80 g paneer", "onion, tomato", "2 toast slices"],
    [
      "Crumble the paneer with your fingers into uneven bits. Frozen paneer can be grated straight from the freezer.",
      "Heat oil in a kadhai. Fry chopped onion until soft, add tomato, chilli, and a pinch of turmeric. Cook until the tomato breaks down.",
      "Add the paneer and salt. Toss on high heat for two minutes so it warms and picks up the masala but does not go dry and rubbery.",
      "Toast the bread. Pile the bhurji on top, or sandwich it. Eat while the toast still crackles.",
    ],
    "Freeze paneer; grate from frozen.",
  ),
  r(
    "Methi or palak thepla leftover",
    8,
    "₹15",
    1,
    ["2 theplas", "curd or pickle"],
    [
      "If the theplas have been in a box overnight, they will be stiff. Do not microwave them into leather.",
      "Heat a tawa on medium. Add a drop of ghee or oil. Warm each thepla thirty seconds a side until it flexes and smells of methi or palak again.",
      "Serve with a bowl of beaten curd and a spoon of pickle. That is breakfast. If you are packing it, roll the thepla around the pickle and wrap it.",
    ],
    "Make eight on Sunday; they travel.",
  ),
  r(
    "Tomato bread upma",
    12,
    "₹18",
    1,
    ["3 bread slices", "1 tomato", "onion, chilli, turmeric"],
    [
      "Cut the bread into small cubes. Stale bread is better; fresh bread turns soggy the moment it meets tomato.",
      "Heat oil, add mustard if you have it, then chopped onion and chilli. When the onion softens, add chopped tomato, turmeric, and salt. Cook until the tomato looks jammy, not watery.",
      "Tip in the bread cubes and toss on medium-high heat so the outside toasts while the masala clings. Do not cover or the bread steams.",
      "Taste for salt. Finish with coriander if you have it. Eat from the kadhai if the plate count is the problem.",
    ],
    "Stale bread is better than fresh.",
  ),
  r(
    "Peanut chutney toast",
    8,
    "₹15",
    1,
    ["2 tbsp roasted peanuts", "chilli, garlic, salt", "bread"],
    [
      "If the peanuts are raw, dry-roast them on a tawa until the skins loosen and they smell cooked. Cool a minute.",
      "Pound them with chilli, a small clove of garlic, and salt in a mortar, or pulse in a mixie without adding water. You want a coarse, dry chutney, not a paste.",
      "Toast the bread. Spread the chutney thick. A smear of ghee or butter under it helps it stick.",
      "Store leftover chutney in a dry steel box. It keeps a week if no wet spoon goes in.",
    ],
    "Keeps a week in a dry box.",
  ),
  r(
    "Daliya (broken wheat) porridge",
    18,
    "₹18",
    1,
    ["1/2 cup daliya", "1.5 cups water or milk", "jaggery or salt-veg"],
    [
      "Dry-roast the daliya in a kadhai on medium heat until it smells like toasted wheat, three minutes. This keeps the porridge from turning gluey.",
      "For a sweet bowl, add milk or water and a pinch of cardamom. For a savoury bowl, add water, salt, and a handful of peas or chopped carrot.",
      "Simmer, stirring, until the grains are soft and have drunk most of the liquid, about twelve minutes. Add a splash more liquid if it seizes.",
      "Sweeten with jaggery off the heat if it is the sweet version, or finish the savoury one with a cumin tadka. Eat hot.",
    ],
    "Savoury daliya with peas is a full meal.",
  ),
  r(
    "Omelette wrap",
    10,
    "₹28",
    1,
    ["2 eggs", "1 roti or tortilla", "onion, sauce"],
    [
      "Beat the eggs with salt and a little chopped onion. Warm the roti on a tawa and keep it aside so it stays pliable.",
      "In the same tawa, pour the eggs and tilt so they make a thin, wide omelette. Cook until the top is just set.",
      "Slide the omelette onto the roti, or build the omelette directly on the roti if you want fewer dishes.",
      "Add sauce or leftover sabzi in a line, roll, and toast the seam. Eat it in the doorway if that is the commute.",
    ],
    "Eat standing up. Still counts as cooking.",
  ),
  r(
    "Curd-rice reset",
    8,
    "₹15",
    1,
    ["1 cup leftover rice", "1/2 cup curd", "salt, tempering optional"],
    [
      "If the leftover rice is fridge-hard, sprinkle a spoon of water and loosen the grains with your fingers or a fork.",
      "Stir in thick curd and salt. Mash a few grains so the bowl turns creamy. Add a splash of milk or water if it is too stiff.",
      "If you have two minutes, heat a teaspoon of oil, pop mustard seeds and a curry leaf, and pour that over the rice. If you do not, eat it as it is.",
      "Serve slightly cool. This is stomach-kind food after a late night, not a showpiece.",
    ],
    "Stomach-kind after a late night.",
  ),
];

const LUNCH = [
  r(
    "Dal tadka rice",
    30,
    "₹25",
    2,
    ["1/2 cup toor or moong dal", "rice", "cumin, garlic, chilli, ghee"],
    [
      "Wash the dal until the water runs clearer. Wash the rice. Put dal in the cooker with double the water, turmeric, and a drop of oil so it does not foam over. In a separate bowl or the cooker separator, put rice with twice its volume of water.",
      "Cook on medium until the cooker gives three whistles, then let the pressure drop on its own. The dal should be soft enough to mash with a spoon.",
      "In a small tadka pan, heat a teaspoon of ghee. Add cumin. When it darkens, add sliced garlic and a dried chilli. Fry until the garlic is gold, not brown.",
      "Pour the tadka over the dal. It should sizzle. Stir, taste for salt, and thin with hot water if it is paste-thick.",
      "Serve the dal on the rice, not beside it, so every spoon has both. This is the cheapest complete plate in the house.",
    ],
    "The cheapest complete protein in the house.",
  ),
  r(
    "Masoor dal and jeera rice",
    25,
    "₹22",
    2,
    ["1/2 cup masoor", "1/2 cup rice", "cumin, onion"],
    [
      "Rinse the masoor; it does not need soaking. Put it in a pan or cooker with twice the water, turmeric, and salt. It will be soft in about twelve minutes on the stove, or two whistles in a cooker.",
      "For the rice, heat a teaspoon of ghee, add a teaspoon of cumin, and when it crackles add the washed rice. Stir one minute so every grain is coated.",
      "Add twice the rice's volume of hot water and a pinch of salt. Cook covered until the water is gone, or two cooker whistles.",
      "In a small pan, fry sliced onion in a little oil until brown at the edges. Stir that into the cooked masoor, or pour it over the rice.",
      "Serve together. Masoor should be pourable, not a brick. Add hot water and simmer two minutes if it has set.",
    ],
    "Red dal is the bachelor's friend.",
  ),
  r(
    "Rajma rice (soaked)",
    45,
    "₹30",
    2,
    ["3/4 cup soaked rajma", "onion-tomato masala", "rice", "chilli, garam masala"],
    [
      "Soak the rajma in plenty of water for at least eight hours. Drain and rinse. Unsoaked rajma will not cook through and is not worth the gas.",
      "Make a masala: fry chopped onion till gold, add ginger-garlic if you have it, then tomato, chilli, and salt. Cook until the oil looks like it is leaving the edges.",
      "Add the soaked rajma and enough water to cover by an inch. Cooker: five to six whistles on medium. The beans should crush easily against the pot.",
      "Mash a handful of beans against the side so the gravy thickens. Add garam masala, simmer five minutes uncovered, and taste for salt.",
      "Serve on plain rice. The plate should be wet enough that you do not need a separate dal.",
    ],
    "Soak before you leave for class.",
  ),
  r(
    "Chole rice",
    40,
    "₹30",
    2,
    ["3/4 cup soaked kabuli chana", "onion-tomato", "chole masala or kitchen king"],
    [
      "Soak kabuli chana overnight. Drain. Cooker them with a pinch of salt and enough water until they are soft, usually four to five whistles.",
      "In a kadhai, cook onion till brown, then tomato and chole masala or kitchen king. This gravy should be darker and thicker than a weekday dal.",
      "Add the cooked chana with some of its cooking liquid. Simmer fifteen minutes so the masala enters the beans, not just coats them.",
      "Mash a few chana to thicken. Taste. A pinch of amchur or a squeeze of lemon at the end wakes it up.",
      "Eat with rice, or with leftover puri if you have that kind of fridge. Canned chana can skip the soak if you are truly late.",
    ],
    "Canned chana works if you are desperate.",
  ),
  r(
    "Weeknight khichdi",
    25,
    "₹18",
    2,
    ["1/2 cup rice", "1/4 cup moong dal", "turmeric, ghee, cumin"],
    [
      "Wash rice and moong dal together until the water is less cloudy. This is one pot; treat them as one grain.",
      "Put them in the cooker with turmeric, salt, and three times their combined volume of water if you want a soft, spoonable khichdi.",
      "Three whistles on medium, then natural release. Stir. If it is stiff, add hot water and a spoon of ghee and simmer two minutes.",
      "In a tadka pan, heat ghee, add cumin, and pour it over the khichdi. The sizzle is the whole recipe announcing it is done.",
      "Eat from a bowl with pickle or papad. This is sick-day food and exam-week food, and that is a compliment.",
    ],
    "Sick-day food and exam-week food.",
  ),
  r(
    "Lemon rice",
    15,
    "₹15",
    1,
    ["2 cups leftover rice", "lemon", "mustard, chilli, peanuts, turmeric"],
    [
      "Use cold leftover rice. Break the clumps with wet fingers so the grains are separate. Hot steaming rice will turn to a lump the moment you toss it.",
      "Heat oil in a kadhai. Pop mustard seeds, add a dried or green chilli, a pinch of turmeric, and a handful of peanuts. Fry the peanuts until they smell roasted.",
      "Add the rice and salt. Toss on medium heat until every grain is yellow and hot, two to three minutes.",
      "Take the kadhai off the heat. Squeeze a whole lemon, toss again, and taste. Add more lemon or salt until it is bright, not just yellow.",
      "Serve at room temperature or warm. Lemon rice packed for later should go in only when fully cool.",
    ],
    "Never toss hot steaming rice or it clumps.",
  ),
  r(
    "Tawa pulao",
    18,
    "₹25",
    1,
    ["leftover rice", "onion, tomato, pav-bhaji masala", "peas or mixed veg"],
    [
      "Heat a wide tawa or kadhai until it is properly hot. Add oil, then sliced onion. Fry on high heat until the edges catch.",
      "Add chopped tomato, a handful of peas or mixed veg, salt, and a generous spoon of pav-bhaji masala. Cook until the tomato collapses and the masala smells cooked, not raw.",
      "Add cold leftover rice. Toss, do not mash. Keep the heat high so the rice fries instead of steaming into a lump.",
      "Taste. Add a knob of butter if you have it, or a squeeze of lemon. Serve at once, straight off the tawa.",
    ],
    "Pav bhaji masala is one tin, many lunches.",
  ),
  r(
    "Egg curry rice",
    25,
    "₹35",
    1,
    ["2 boiled eggs", "onion-tomato gravy", "rice"],
    [
      "Boil the eggs eight minutes, cool, peel, and halve them. If you are cooking rice in the cooker, you can boil the eggs in a small bowl on the separator in the same run.",
      "Fry onion till gold, add tomato, chilli, turmeric, and salt. Cook the gravy until it thickens and the oil separates at the rim.",
      "Slide the halved eggs in, cut side down first so they pick up colour. Spoon gravy over them and simmer three minutes. Do not stir hard or the yolks will crumble into the sauce.",
      "Serve on rice with enough gravy to wet the plate. A pinch of garam masala at the end is optional and good.",
    ],
    "Boil eggs in the same cooker as rice.",
  ),
  r(
    "Aloo gobi roti",
    30,
    "₹22",
    2,
    ["1 potato", "1/2 cauliflower", "roti atta", "jeera, turmeric"],
    [
      "Cut the potato and cauliflower, including the tender stem, into small even pieces so they cook together. Wash the gobi well; grit hides in the florets.",
      "Heat oil, add jeera, then the potato. Fry three minutes before you add the cauliflower, so the potato gets a head start.",
      "Add turmeric, chilli, and salt. Cover and cook on medium-low, stirring once, until both vegetables are tender and the moisture has dried. This is a dry sabzi for roti, not a gravy.",
      "Meanwhile knead atta with water and a pinch of salt into a soft dough. Rest five minutes. Roll thin rotis and cook on a hot tawa until both sides have brown spots, finishing with a direct flame if you have one.",
      "Eat the sabzi inside the roti, or beside it. A spoon of pickle is enough of a side.",
    ],
    "Cauliflower stem is edible. Use it.",
  ),
  r(
    "Bhindi masala roti",
    25,
    "₹22",
    1,
    ["200 g bhindi", "onion, amchur", "roti"],
    [
      "Wipe the bhindi dry with a cloth. Water is what makes it slime. Trim the tops and cut into two-centimetre pieces.",
      "Heat a wide pan with enough oil to coat the base. Add the bhindi on medium heat and leave it alone for two minutes before the first stir.",
      "When the slime has cooked off and the pieces look drier, add sliced onion, chilli, and salt. Salt at the end, not the start, or the bhindi weeps.",
      "Finish with a pinch of amchur. Cook until the onion is soft and the bhindi is tender with browned edges.",
      "Serve with rotis made while the sabzi finishes. Two rotis and this pan is lunch.",
    ],
    "Salt at the end.",
  ),
  r(
    "Palak dal",
    30,
    "₹22",
    2,
    ["dal", "2 cups chopped palak", "garlic tadka"],
    [
      "Cook toor or moong dal in the cooker with turmeric and water until soft, three whistles. Mash it lightly.",
      "Wash the palak well; sand lives in the stems. Chop roughly. Frozen palak can go in from the packet; just cook it a minute longer.",
      "Add the palak to the dal and simmer five minutes so the leaves wilt and the dal turns green at the edges. Add salt now.",
      "Heat ghee or oil, fry sliced garlic until gold, and pour it over the dal. The garlic should smell sweet, not burnt.",
      "Serve with rice or roti. If the dal is too thick, loosen with hot water. If it is watery, simmer uncovered a few minutes.",
    ],
    "Frozen palak is allowed.",
  ),
  r(
    "Sambar rice (shortcut)",
    30,
    "₹25",
    2,
    ["toor dal", "sambar powder", "tamarind or lemon", "onion, veg"],
    [
      "Cook toor dal with chopped onion, a handful of whatever vegetable you have — drumstick, pumpkin, carrot, or frozen mix — and enough water for a loose dal, three cooker whistles.",
      "Mash the dal slightly. Stir in a heaped spoon of sambar powder and salt. Simmer five minutes so the powder cooks and does not taste raw.",
      "Add a marble of tamarind soaked in a little water, or a good squeeze of lemon if that is what you have. The sour should show up clearly.",
      "Temper mustard seeds, curry leaf, and a dried chilli in oil. Pour over the sambar.",
      "Spoon it over rice so the rice sits in the liquid. This is shortcut sambar, not a festival; it still beats skipping lunch.",
    ],
    "A box of sambar powder earns its shelf space.",
  ),
  r(
    "Curd rice lunch",
    10,
    "₹18",
    1,
    ["rice", "curd", "cucumber", "tempering"],
    [
      "Use rice that has cooled enough to touch. Hot rice will split the curd and make it watery.",
      "Mash the rice with thick curd, salt, and a splash of milk until it is creamy. Fold in finely chopped cucumber.",
      "If you have two minutes, temper mustard, a pinch of grated ginger, and a green chilli in oil, and stir that through.",
      "Eat slightly cool. Pack extra rice if this is a tiffin; curd rice vanishes and you will be hungry at four.",
    ],
    "Pack extra rice; curd rice vanishes.",
  ),
  r(
    "Mix-veg rice",
    25,
    "₹22",
    2,
    ["rice", "frozen mixed veg", "whole spices", "onion"],
    [
      "Wash half a cup of rice. Heat oil in the cooker, add a bay leaf or a cinnamon stick if you have one, then sliced onion. Fry until the onion is soft.",
      "Add a cup of frozen mixed veg straight from the bag. Stir one minute so the ice melts and the spices can cling.",
      "Add the rice, salt, and twice the rice's volume of water. Close the cooker. Two to three whistles on medium.",
      "Let the pressure drop. Fluff with a fork. Serve with curd or a fried egg if the vegetables look lonely.",
    ],
    "Frozen veg is cheaper than wilted fresh veg.",
  ),
  r(
    "Budget chicken curry rice",
    35,
    "₹70",
    2,
    ["250 g chicken", "onion-tomato", "rice", "kitchen king"],
    [
      "Pat the chicken dry. If it is on the bone, leave the bone; it makes a better gravy. Sprinkle salt and a little chilli.",
      "Fry sliced onion till deep gold — this is the colour of the curry. Add ginger-garlic if you have it, then tomato and kitchen king. Cook until the masala looks tight and shiny.",
      "Add the chicken and stir until every piece is coated and the raw edges turn white. Add half a cup of water.",
      "Cooker: three whistles on medium, then natural release. Open, taste, and simmer uncovered if you want the gravy thicker.",
      "Serve half with rice today. Cool the rest and refrigerate. Tomorrow it will taste more like a curry and still be cheaper than one delivery order.",
    ],
    "Split over two lunches. Still cheaper than delivery.",
  ),
  r(
    "Egg fried rice",
    12,
    "₹28",
    1,
    ["leftover rice", "1–2 eggs", "soy sauce, garlic, spring onion or regular onion"],
    [
      "Use only cold leftover rice. Break clumps with wet hands. Hot rice will smash into a porridge the moment it hits the pan.",
      "Heat a kadhai until it is properly hot. Add oil, then chopped garlic and onion. Fry twenty seconds until the garlic is fragrant, not brown.",
      "Push the onion aside. Pour in beaten eggs and scramble them in that space until just set.",
      "Add the rice and a splash of soy sauce. Toss on high heat until the grains are hot and a few are toasted. Finish with chopped spring onion or more onion.",
      "Taste. Add salt only after the soy. Serve at once; fried rice waits badly.",
    ],
    "Cold rice only.",
  ),
  r(
    "Soya chunk curry",
    25,
    "₹25",
    2,
    ["1 cup soya chunks", "onion-tomato", "garam masala"],
    [
      "Boil the soya chunks in salted water for five minutes. They will swell. Drain and squeeze them hard in your fist until they stop dripping. This step is the whole recipe; wet soya tastes like sponge.",
      "Fry onion till gold, add tomato, chilli, turmeric, and salt. Cook the gravy until the raw tomato smell goes.",
      "Add the squeezed soya and a splash of water. Fry two minutes so the chunks take colour, then simmer in the gravy ten minutes.",
      "Finish with garam masala. Taste. The chunks should be juicy and seasoned all the way through, not just on the outside.",
      "Serve with rice or roti. This is protein without the meat bill, and it reheats well.",
    ],
    "Protein without the meat bill.",
  ),
  r(
    "Chana masala (brown chana)",
    35,
    "₹20",
    2,
    ["soaked kala chana", "onion-tomato", "amchur"],
    [
      "Soak kala chana overnight. Drain and cooker them with water and a pinch of salt until they are soft, four to five whistles. They take longer than kabuli.",
      "Make an onion-tomato masala and cook it darker than you would for dal. Add the chana and some cooking liquid.",
      "Simmer until the gravy clings and a few chana have burst. Mash those against the pot.",
      "Finish with amchur. Taste for salt and sour. Serve with rice or as a dry-ish sabzi with roti.",
    ],
    "Kala chana is cheaper than kabuli.",
  ),
  r(
    "Lauki chana dal",
    30,
    "₹18",
    2,
    ["1/2 lauki", "chana dal", "turmeric, tadka"],
    [
      "Peel the lauki, taste a scrap near the seed; if it is bitter, throw the vegetable away. Cut the rest into half-moons. Pick a lauki that feels heavy for its size.",
      "Wash chana dal. Put dal, lauki, turmeric, and water in the cooker. Three to four whistles until the dal is soft and the lauki collapses.",
      "Mash lightly so the bowl is stew-like, not watery soup. Add salt.",
      "Temper cumin, garlic, or both in ghee and pour over. Serve with rice. Mild food is allowed; bland food is a salt problem.",
    ],
    "Buy lauki that feels heavy.",
  ),
  r(
    "Capsicum-potato dry",
    20,
    "₹18",
    1,
    ["1 capsicum", "1 potato", "jeera, chilli"],
    [
      "Dice the potato small. Cut the capsicum into similar pieces so they look like they belong on the same plate.",
      "Heat oil, add jeera, then the potato and a pinch of salt. Cover and cook on medium until the potato is almost tender, about eight minutes, stirring once.",
      "Add the capsicum and chilli. Cook uncovered on a higher flame so the capsicum stays green and slightly crisp, not grey and collapsed.",
      "Taste. This should be dry enough to stuff into a roti. If there is water in the pan, cook it off.",
    ],
    "Works as a roti stuffing.",
  ),
  r(
    "Tomato rasam rice",
    20,
    "₹15",
    1,
    ["2 tomatoes", "rasam powder or cumin-pepper", "tamarind pinch", "rice"],
    [
      "Chop the tomatoes and put them in a pan with two cups of water, a pinch of turmeric, and salt. Boil until they slump, then mash them against the side.",
      "Stir in a spoon of rasam powder, or crush cumin and pepper and add that. A small piece of tamarind or a squeeze of lemon gives the sour.",
      "Simmer five minutes. The liquid should taste sharp and thin, like a soup you pour, not a gravy you scoop.",
      "Temper mustard seeds in oil and pour over. Ladle the rasam over hot rice. This is the lunch you make when a heavy plate feels impossible.",
    ],
    "When you cannot face a heavy lunch.",
  ),
  r(
    "Kadhi and rice",
    30,
    "₹20",
    2,
    ["1 cup curd", "2 tbsp besan", "methi seeds, chilli"],
    [
      "Whisk the curd until smooth, then whisk in the besan so there are no lumps. Add two cups of water and salt. Sour curd is better than sweet fresh curd here.",
      "Pour into a kadhai and set it on medium-low. Stir often as it comes up to a simmer. Do not let it boil hard or the curd will split.",
      "Cook ten to fifteen minutes until it thickens enough to coat a spoon and the raw besan smell is gone.",
      "Temper methi seeds and a dried chilli in ghee or oil — methi turns bitter if it burns, so twenty seconds is enough — and pour over the kadhi.",
      "Serve with plain rice. The plate should be soupy. Kadhi thickens as it sits; loosen with hot water when you reheat.",
    ],
    "Sour curd is a feature.",
  ),
  r(
    "Vegetable tahiri",
    30,
    "₹22",
    2,
    ["rice", "potato, peas", "whole spices"],
    [
      "Heat oil in the cooker. Add a bay leaf, a clove or two, or whatever whole spice is in the box. Add sliced onion and fry until soft.",
      "Add cubed potato and peas, then turmeric, chilli, and salt. Stir so the potato is coated.",
      "Add washed rice and twice its volume of water. Two to three cooker whistles.",
      "Rest five minutes after the pressure drops, then fluff. Eat with raita or plain curd. This is biryani's poorer cousin, and it does not owe anyone an apology.",
    ],
    "The poor cousin of biryani, and proud.",
  ),
  r(
    "Small-batch matar paneer",
    25,
    "₹45",
    1,
    ["80 g paneer", "1/2 cup peas", "onion-tomato"],
    [
      "Cube the paneer. If it is rubbery from the fridge, soak the cubes in warm water for five minutes and drain.",
      "Cook onion till gold, add tomato, chilli, and a pinch of kitchen king or garam masala. Cook until the gravy is thick and the oil shows.",
      "Add the peas and a splash of water. Simmer until the peas are tender.",
      "Slide the paneer in for the last three minutes only. Stir gently. Long frying makes paneer bounce.",
      "Taste for salt. Serve with roti or rice. This is a small batch on purpose; leftover paneer gravy dries out overnight.",
    ],
    "Do not fry paneer to rubber.",
  ),
  r(
    "One-pot tomato dalcha",
    30,
    "₹20",
    2,
    ["masoor", "tomato", "garlic", "rice"],
    [
      "Put washed masoor, chopped tomato, a few garlic cloves, turmeric, and water in the cooker. Three whistles.",
      "Open and mash the dal and tomato together into a loose stew. Add salt. If it is thick, add hot water; if it is thin, simmer uncovered.",
      "Temper cumin or more garlic in ghee and pour over. There is no coconut in this version, and you will not miss it.",
      "Spoon the stew over rice. It should be wet enough to eat with a spoon, not a dry scoop.",
    ],
    "No coconut needed.",
  ),
];

const SNACKS = [
  r(
    "Masala peanuts",
    8,
    "₹15",
    1,
    ["1 handful peanuts", "chilli, salt, chaat masala", "drop of oil"],
    [
      "Put a handful of raw peanuts on a dry tawa on medium-low heat. Stir every half minute so the ones at the edge do not burn.",
      "When the skins darken and the nuts smell roasted, about five minutes, add a drop of oil if you want the spices to cling.",
      "Take the tawa off the heat. Add salt, chilli powder, and chaat masala. Toss while the nuts are hot.",
      "Cool a minute so they crisp, then eat from a bowl. A packet of chips costs more and lasts two minutes.",
    ],
    "Better than a ₹40 chip packet.",
  ),
  r(
    "Roasted chana",
    5,
    "₹10",
    1,
    ["roasted chana", "onion, chilli, lemon"],
    [
      "Put a bowl of roasted chana on the table, not the open packet. The packet is how you eat the week's stash in one sitting.",
      "Add finely chopped onion and green chilli. Squeeze lemon over and toss.",
      "Eat with a spoon. If it tastes dry, add another squeeze of lemon, not more chana.",
    ],
    "Keep a jar at the desk.",
  ),
  r(
    "Paper bhel",
    8,
    "₹20",
    1,
    ["2 cups murmura", "onion, tomato, coriander", "chutney or lemon + chilli"],
    [
      "If the murmura is soft, sun it for ten minutes or toss it on a dry tawa for a minute until it crackles again.",
      "Chop onion, tomato, and coriander small. Keep them ready; once the murmura is wet you cannot wait.",
      "In a wide bowl toss murmura with the vegetables, salt, and either green chutney or lemon plus chilli powder. Sev on top is optional.",
      "Eat immediately, standing if you must. Five minutes later it is soggy and the point is lost.",
    ],
    "Sev is optional, not the point.",
  ),
  r(
    "Masala corn",
    10,
    "₹20",
    1,
    ["1 cup boiled corn", "butter or oil", "chilli, chaat masala, lemon"],
    [
      "If the corn is frozen, boil or microwave it until the kernels are hot and tender. Drain well so water does not drown the masala.",
      "Heat a small pan, add a knob of butter or a drop of oil, and toss the corn on high heat for a minute.",
      "Take it off the heat. Add chilli powder, chaat masala, salt, and lemon. Toss again.",
      "Eat hot from the pan. Cold masala corn is just wet maize.",
    ],
    "Frozen corn is fine.",
  ),
  r(
    "Chilli cheese toast",
    8,
    "₹30",
    1,
    ["2 bread slices", "cheese", "green chilli, oregano or chilli flakes"],
    [
      "Lay the bread on a tawa or a plate. Cover each slice with cheese, chopped green chilli, and a pinch of oregano or chilli flakes.",
      "If you have a grill or oven, use it. On a tawa, cover the pan so the trapped heat melts the cheese before the bread burns.",
      "Cook on medium-low until the cheese slumps and the underside is gold, three to four minutes.",
      "One slice is a snack. Two slices with tea is dinner and you do not have to pretend otherwise.",
    ],
    "One toast is a snack. Two is dinner.",
  ),
  r(
    "Bread pizza",
    12,
    "₹35",
    1,
    ["2 bread slices", "pizza sauce or ketchup-chilli", "onion, capsicum, cheese"],
    [
      "Mix ketchup with chilli flakes if you have no pizza sauce. Spread a thin layer on the bread; too much sauce makes a soggy raft.",
      "Scatter chopped onion and capsicum, then cheese. Do not pile so high that the topping slides off when you lift it.",
      "Set the slices on a medium tawa and cover. Cook until the cheese melts and the bread base is crisp, four to five minutes.",
      "Cut into four if you are sharing, or do not share. This is not Naples. It is still better than being hungry.",
    ],
    "Not Naples. Still better than hunger.",
  ),
  r(
    "Upgraded Maggi",
    8,
    "₹25",
    1,
    ["1 Maggi", "egg or frozen peas", "onion, chilli"],
    [
      "Boil the Maggi in a little more water than the packet asks, with chopped onion, chilli, and a handful of frozen peas if you have them.",
      "When the noodles are almost soft, push them aside and crack an egg into the pan. Scramble it into the water, then fold it through the noodles.",
      "Add the tastemaker. Cook off extra water so you have a coated pile, not a soup, unless soup is what you wanted.",
      "Eat from the pan. The packet is a base. The egg and onion are the part that makes it food.",
    ],
    "The packet is a base, not a personality.",
  ),
  r(
    "Onion pakora (small)",
    15,
    "₹18",
    1,
    ["1 onion", "4 tbsp besan", "ajwain, oil for shallow fry"],
    [
      "Slice one onion thin. Toss it with salt and leave two minutes so it weeps. That moisture is what binds the batter; you need very little water.",
      "Add besan, ajwain, and chilli. Mix into a thick coat that clings to the onion. If it is runny, add a spoon more besan.",
      "Heat a thin layer of oil in a kadhai — enough to shallow-fry, not a litre for a party you are not hosting.",
      "Drop small clumps. Fry on medium until both sides are brown and the onion inside is sweet, about three minutes a side. Drain on paper.",
      "Eat with tea or ketchup. Make only this many. Leftover pakora in a box is a regret.",
    ],
    "Enough for tea, not a party.",
  ),
  r(
    "Sweet potato chaat",
    20,
    "₹20",
    1,
    ["1 sweet potato", "chaat masala, lemon, chilli"],
    [
      "Wash the sweet potato. Boil it whole until a knife slides in, about fifteen minutes, or microwave it on a wet plate for six to eight minutes, turning once.",
      "Cool just enough to handle. Peel if the skin is tough, or leave it. Cube the flesh.",
      "Toss with chaat masala, chilli powder, salt, and plenty of lemon. Taste; it should be sweet, sour, and hot in the same bite.",
      "Eat warm. This fills you longer than a sleeve of biscuits and costs less than a café snack.",
    ],
    "Fills you longer than biscuits.",
  ),
  r(
    "Fruit chaat",
    7,
    "₹25",
    1,
    ["banana, apple or seasonal fruit", "chaat masala, lemon"],
    [
      "Wash and cube whatever fruit you have. Slightly ugly fruit is cheaper and tastes the same once it is cut.",
      "Toss with chaat masala, a pinch of salt, and lemon. The lemon slows browning and is the seasoning.",
      "Eat within ten minutes. Banana and apple both darken, and a brown chaat is still edible but looks like you gave up.",
    ],
    "Buy fruit that is slightly ugly and cheaper.",
  ),
  r(
    "Cucumber tomato sandwich",
    6,
    "₹15",
    1,
    ["bread", "cucumber, tomato", "salt, pepper, butter optional"],
    [
      "Slice the cucumber thin. Salt it and wait two minutes, then squeeze the slices in your fist. Skip this and the sandwich is a wet sponge.",
      "Slice tomato thin. Butter the bread if you have butter; it is a waterproof layer as much as a flavour.",
      "Stack cucumber, tomato, pepper, and a pinch more salt. Close and press. Cut and eat at once.",
    ],
    "Watery sandwich means you skipped the squeeze.",
  ),
  r(
    "Leftover roti chips",
    8,
    "₹8",
    1,
    ["2 stale rotis", "oil, chilli, salt"],
    [
      "Stale rotis that crack when you fold them are the right ones. Fresh rotis will not crisp.",
      "Cut them into triangles. Heat a thin film of oil on a tawa. Lay the pieces in a single layer.",
      "Cook on medium, turning, until both sides are blistered and crisp, about three minutes. Sprinkle salt and chilli while they are hot.",
      "Cool a minute so they harden. Eat with tea or with leftover dal as a scoop.",
    ],
    "Stale roti is an ingredient.",
  ),
  r(
    "Egg toast fingers",
    8,
    "₹22",
    1,
    ["1 egg", "2 bread slices", "salt, chilli"],
    [
      "Beat the egg with salt and chilli in a shallow plate. Cut the bread into three fingers each.",
      "Heat a tawa with a little oil or butter on medium. Dip each finger so it is coated, not soaked to the crumb.",
      "Fry two minutes a side until the egg is set and the edges are brown.",
      "Eat with ketchup, standing at the tawa if it is 11 p.m. and that is the only plan.",
    ],
    "Works at 11 p.m.",
  ),
  r(
    "Roasted makhana",
    8,
    "₹25",
    1,
    ["2 cups makhana", "ghee, salt, chilli or turmeric"],
    [
      "Heat a wide kadhai on low. Add a teaspoon of ghee and the makhana. They burn on high heat and stay chewy on a rush.",
      "Stir and toss for six to eight minutes until a makhana crushes cleanly between your teeth and sounds hollow.",
      "Take the pan off the heat. Add salt and chilli or turmeric. Toss. They crisp further as they cool.",
      "Store what you do not eat in a dry jar. A film and a full bag is how the bag disappears.",
    ],
    "A whole bag lasts days if you do not watch a film.",
  ),
  r(
    "Peanut masala chaat",
    6,
    "₹15",
    1,
    ["boiled or roasted peanuts", "onion, coriander, lemon"],
    [
      "If you have raw peanuts, boil them in salted water for fifteen minutes, drain, and cool slightly. Roasted peanuts can skip the boil.",
      "Toss with chopped onion, coriander, salt, chilli, and lemon in a bowl.",
      "Eat at once while the peanuts are still warm if boiled, or crunchy if roasted. This is a desk snack that looks like you meant it.",
    ],
    "Boil raw peanuts with salt for 15 minutes.",
  ),
  r(
    "Instant buttermilk",
    4,
    "₹10",
    1,
    ["3 tbsp curd", "water", "salt, jeera, chilli"],
    [
      "Put the curd in a tall glass. Add a pinch of salt, roasted jeera powder if you have it, and a little chilli.",
      "Add cold water to fill the glass. Beat with a fork until there are no lumps and a light foam sits on top.",
      "Add an ice cube if the fridge has one. Drink it in the afternoon when a bottled drink would have cost four times this.",
    ],
    "Cheaper than a bottled drink.",
  ),
  r(
    "Salt lassi",
    5,
    "₹15",
    1,
    ["1/2 cup curd", "water", "salt, cumin"],
    [
      "Beat thick curd in a bowl until it is smooth and has increased a little in volume.",
      "Add cold water, salt, and a pinch of cumin. Beat again until frothy.",
      "Taste. It should be salty and thin enough to drink, not a raita. Sugar is a different drink; do not add it here unless you meant to.",
    ],
    "Sweet lassi is optional sugar, not a rule.",
  ),
  r(
    "Banana lassi",
    5,
    "₹20",
    1,
    ["1 banana", "curd", "sugar pinch"],
    [
      "Use an overripe banana; the brown spots are sugar you do not have to buy. Mash it in a bowl with a fork until it is almost a puree.",
      "Add thick curd and a pinch of sugar or none. Beat hard until the drink is smooth enough to sip. A mixie is nicer; a fork is enough.",
      "Add a splash of water or milk if it is too thick. Drink at once before the banana oxidises and the top turns grey.",
    ],
    "Use overripe bananas.",
  ),
  r(
    "Sprouts sundal",
    10,
    "₹15",
    1,
    ["sprouts or boiled chana", "coconut optional", "mustard tadka"],
    [
      "If you are using dried chana, they should already be boiled and drained. Sprouts can be used as they are, or steamed two minutes.",
      "Heat a teaspoon of oil. Pop mustard seeds, add a pinch of hing if you have it, and a slit chilli.",
      "Add the sprouts or chana and salt. Toss two minutes until they are hot and coated.",
      "Finish with grated coconut if the budget allows. Skip it if it does not; the tadka is the flavour. Eat warm, like a canteen plate.",
    ],
    "Skip coconut if the budget is tight.",
  ),
  r(
    "Microwave mug cake",
    6,
    "₹20",
    1,
    ["4 tbsp atta or maida", "3 tbsp sugar", "3 tbsp milk", "1 tbsp oil, cocoa optional"],
    [
      "In a microwave-safe mug mix atta or maida, sugar, milk, oil, and a spoon of cocoa if you want it chocolate. Stir until there are no dry pockets at the bottom.",
      "The batter should be thick but pourable. Tap the mug once to release big bubbles.",
      "Microwave on high for about ninety seconds. It will rise and then sink. That is normal. A wet centre means twenty seconds more.",
      "Wait a minute so you do not burn your mouth. Eat from the mug with a spoon. It is a cake the size of a mood, not a bakery.",
    ],
    "It sinks. Eat it anyway.",
  ),
  r(
    "Hummus toast (blender)",
    10,
    "₹25",
    1,
    ["1/2 cup boiled chana", "lemon, garlic, oil", "toast"],
    [
      "If the chana is fridge-cold, warm it slightly so it mashes. A mixie makes a smoother hummus; a masher and some faith also work.",
      "Mash or blend the chana with a small clove of garlic, a good squeeze of lemon, salt, and a spoon of oil. Add a splash of the boiling water or plain water until it is spreadable.",
      "Taste. It should be lemony first, garlicky second. Tahini is optional and expensive; lemon is not.",
      "Toast the bread and spread the hummus thick. Olive oil on top if you are feeling rich; chilli flakes if you are not.",
    ],
    "Tahini is optional. Lemon is not.",
  ),
  r(
    "Masala popcorn",
    8,
    "₹12",
    1,
    ["1/4 cup corn kernels", "oil, salt, chilli"],
    [
      "Heat a spoon of oil in a kadhai with a tight lid. Add two kernels as testers. When they pop, the oil is ready.",
      "Add the rest of the kernels, cover, and shake the kadhai now and then so nothing sits on a hot spot and burns.",
      "When the popping slows to two seconds between pops, take it off the heat. Leave the lid on another thirty seconds.",
      "Salt and chilli while it is hot. Pour into a bowl. This is a cinema without the ticket, and the oil is cheaper than a small tub.",
    ],
    "A cinema without the ticket.",
  ),
  r(
    "Raita cup",
    5,
    "₹12",
    1,
    ["curd", "cucumber or onion", "salt, jeera"],
    [
      "Beat the curd until it is smooth and loose. If it is very thick, add a spoon of water.",
      "Stir in finely chopped cucumber or onion, salt, and a pinch of roasted jeera.",
      "Taste. Eat it as a snack with papad, or put the cup next to khichdi and call it a side.",
    ],
    "Snack or a side for khichdi.",
  ),
  r(
    "Chutney-curd dip + biscuits",
    4,
    "₹15",
    1,
    ["curd", "green chutney or pickle oil", "cheap glucose biscuits"],
    [
      "Put a few spoons of curd in a bowl. Swirl in green chutney, or a little oil from the pickle jar if that is the only condiment left.",
      "Do not overmix; you want streaks, not a uniform green soup.",
      "Dip glucose biscuits and eat. It is not elegant. It is effective, and it is dinner-adjacent at 6 p.m.",
    ],
    "Not elegant. Effective.",
  ),
  r(
    "Boiled-peanut evening plate",
    20,
    "₹15",
    1,
    ["raw peanuts", "salt"],
    [
      "Put raw peanuts in a pan, cover with water, and add a teaspoon of salt. The water should taste like the sea or the peanuts will be bland inside.",
      "Boil fifteen to twenty minutes until a peanut presses soft and the skin slips if you pinch it.",
      "Drain. Pile them on a plate. Eat warm, slipping the skins as you go.",
      "The house will smell like a train snack. That is the point. Do not fry them afterwards; you already cooked them.",
    ],
    "The whole house will smell like a train snack. That is the point.",
  ),
];

const DINNER = [
  r(
    "One-pan egg rice",
    15,
    "₹28",
    1,
    ["leftover rice", "2 eggs", "soy or chilli sauce", "onion"],
    [
      "Use leftover rice and break the clumps. Heat oil in the kadhai you are already annoyed about washing.",
      "Fry chopped onion until soft. Push it aside, pour in two beaten eggs, and scramble them in that space until just set.",
      "Add the rice and toss on high heat until everything is hot and a few grains catch on the pan.",
      "Splash soy or chilli sauce around the edge of the pan, not on one spot, then toss once more. Taste for salt.",
      "Eat from the kadhai. Dinner and washing are the same object. That is the recipe.",
    ],
    "Dinner in the same kadhai you resent washing.",
  ),
  r(
    "Dal fry and roti",
    30,
    "₹22",
    1,
    ["moong or toor", "atta", "ghee tadka"],
    [
      "Wash the dal and cooker it with turmeric and water, three whistles. Mash it to a spoonable texture and add salt.",
      "Knead atta with water into a soft dough while the cooker hisses. Rest the dough five minutes.",
      "Make a tadka of ghee, cumin, and garlic or chilli. Pour it over the dal and simmer two minutes so the fat mixes in.",
      "Roll two rotis and cook them on a hot tawa, finishing on the flame if you can. Stack them wrapped in a cloth.",
      "Sit down with dal and roti. If you can make this without a recipe card, you can live alone. That is the test, not the flavour.",
    ],
    "If you can make this, you can live alone.",
  ),
  r(
    "Vegetable soup and toast",
    20,
    "₹20",
    1,
    ["onion, carrot, cabbage", "pepper, salt", "2 toast slices"],
    [
      "Chop onion, carrot, and cabbage small so they soften in one pan. Heat a drop of oil, fry the onion one minute, then add the rest.",
      "Add water to cover, salt, and a lot of pepper. Stock cubes are optional; the onion is not. Boil twelve minutes until the carrot gives.",
      "Mash half the vegetables against the side so the soup thickens without cream. Taste and add more pepper than you think is polite.",
      "Toast two slices of bread. Eat the soup with the toast dipped in. This is a full dinner on a night you cannot face masala.",
    ],
    "Stock cubes are optional; onion is not.",
  ),
  r(
    "Paneer bhurji dinner",
    15,
    "₹40",
    1,
    ["100 g paneer", "onion-tomato", "roti or rice"],
    [
      "Crumble the paneer. If you are short, double the onion so the pan still looks full.",
      "Fry onion on high heat until the edges brown. Add tomato, chilli, and salt. Cook until the tomato is soft but the pan is still dry-ish.",
      "Add the paneer, toss one minute, and stop. Soft bhurji is the aim. Another three minutes and you have rubber for roti.",
      "Serve with roti or on rice. Eat at once. Reheated paneer bhurji is possible and never as good.",
    ],
    "Double the onion if paneer is short.",
  ),
  r(
    "Soya keema roti",
    25,
    "₹25",
    2,
    ["soya granules", "onion, garlic, kitchen king"],
    [
      "Soak soya granules in hot water for ten minutes. Drain and squeeze until your hands are tired. Wet granules will not fry; they will steam.",
      "Heat oil, add chopped garlic and onion, and fry until the onion is brown at the edges.",
      "Add the squeezed granules, kitchen king, chilli, and salt. Fry on medium-high, pressing with the spoon, until the mix looks like keema and smells roasted, six to eight minutes.",
      "Splash a spoon of water if it sticks, then dry it off again. Taste. It should taste like you tried, not like wet cardboard.",
      "Serve with roti. The second plate keeps for tomorrow's lunch.",
    ],
    "Tastes like you tried.",
  ),
  r(
    "Cabbage peas sabzi",
    18,
    "₹15",
    1,
    ["1/2 cabbage", "peas", "jeera, turmeric"],
    [
      "Shred half a cabbage. A whole cabbage is three dinners; bag the rest.",
      "Heat oil, add jeera, then the cabbage and a handful of peas. Add turmeric and salt.",
      "Cook on high heat, stirring often, so the cabbage wilts and sweetens but does not sit in its own water and boil grey.",
      "When it is tender-crisp and dry, stop. Serve with roti or as a side to dal. Overcooked cabbage is why people think they hate cabbage.",
    ],
    "A whole cabbage is three dinners.",
  ),
  r(
    "Aloo matar",
    20,
    "₹18",
    1,
    ["2 potatoes", "1/2 cup peas", "onion-tomato or dry jeera"],
    [
      "Cube the potatoes small. Frozen peas can go in from the bag.",
      "For a gravy: fry onion, add tomato and masala, then potato, peas, and water. Cooker two whistles, or simmer on the tawa fifteen minutes until the potato is soft.",
      "For a dry version: heat oil, add jeera, potato, peas, turmeric, and salt. Cover and cook, stirring once, until the potato is done.",
      "Taste and add amchur or lemon if it is flat. This is the national emergency dinner. Keep potatoes in the house.",
    ],
    "The national emergency dinner.",
  ),
  r(
    "Jeera aloo and dal",
    25,
    "₹18",
    1,
    ["potatoes", "cumin, chilli", "simple dal"],
    [
      "If you thought ahead, boil the potatoes in the morning. If you did not, cooker them now, two whistles, then peel and crush roughly.",
      "Put a simple moong or masoor dal on in the cooker at the same time, three whistles, and mash with salt.",
      "Heat oil or ghee, add plenty of cumin and a dried chilli. When the cumin darkens, add the crushed potato and salt. Fry until the edges crisp.",
      "Serve the jeera aloo and the dal in two bowls, or on one plate with roti. Two pans, still under half an hour if the potatoes were ready.",
    ],
    "Two pans, still under half an hour.",
  ),
  r(
    "Palak egg",
    20,
    "₹30",
    1,
    ["palak", "2 eggs", "garlic"],
    [
      "Wash a bunch of palak and chop it. Fry sliced garlic in a little oil, then add the palak and salt. It will look like too many leaves. It will wilt.",
      "Cook until the palak is soft and most of the water has gone, five to seven minutes. Spread it into an even bed.",
      "Make two wells with the spoon. Crack an egg into each. Sprinkle salt and chilli on the yolks.",
      "Cover the pan on low heat until the whites are set and the yolks are as runny as you like, four to six minutes.",
      "Eat from the pan with toast or roti. It looks like a café plate. It is a bunch of greens and two eggs.",
    ],
    "Looks fancy. Is not.",
  ),
  r(
    "Tomato egg drop",
    15,
    "₹22",
    1,
    ["3 tomatoes", "2 eggs", "garlic, sugar pinch"],
    [
      "Chop the tomatoes. Fry a little garlic in oil, add the tomatoes, salt, and a pinch of sugar to cut the acid. Cook until they collapse into a jam, eight minutes.",
      "Beat the eggs in a cup. With the tomato on a medium simmer, drizzle the egg in a thin stream while you stir slowly so it sets in ribbons, not one omelette.",
      "Cook one more minute until the egg is just done. Taste. The pan should be saucy.",
      "Spoon over rice or toast. This is the dinner for when there is nothing in the fridge but tomatoes and eggs, which is often.",
    ],
    "Rice or toast underneath.",
  ),
  r(
    "Mushroom masala",
    20,
    "₹40",
    1,
    ["200 g mushroom", "onion-tomato", "pepper"],
    [
      "Wipe the mushrooms with a damp cloth. Do not hold them under the tap; they drink water and then stew instead of fry. Quarter them.",
      "Heat a wide pan until it is hot. Add oil and the mushrooms with a pinch of salt. Cook on high heat until they release water and then that water evaporates and they brown.",
      "Push them aside, add onion and then tomato, chilli, and pepper. Cook the masala, then fold the mushrooms back in for three minutes.",
      "Taste. Buy mushrooms when they are on discount; at full price this is a treat plate, not a Tuesday habit.",
    ],
    "When they are on discount.",
  ),
  r(
    "Budget pasta masala",
    18,
    "₹30",
    1,
    ["80 g pasta", "onion, tomato, chilli flakes", "cheese optional"],
    [
      "Boil the pasta in well-salted water until it is just tender. Before you drain, scoop out a mug of the cloudy water and keep it.",
      "In a kadhai, fry onion, add chopped tomato and chilli flakes, and cook until you have a thick masala, not raw ketchup sitting on noodles.",
      "Add the drained pasta and a splash of the pasta water. Toss until the sauce clings. The starch in the water is what makes it look like a real plate.",
      "Grate cheese on top if you have it. Taste for salt. Eat at once; leftover masala pasta clumps in the box.",
    ],
    "Save a splash of pasta water.",
  ),
  r(
    "Veg noodles",
    15,
    "₹25",
    1,
    ["1 noodle cake", "cabbage, carrot", "soy, vinegar pinch"],
    [
      "Boil the noodle cake until just loose, then drain and toss with a drop of oil so the strands do not weld together.",
      "In a hot kadhai, stir-fry shredded cabbage and carrot for two minutes so they stay crisp. Add garlic if you have it.",
      "Add the noodles, soy sauce, a pinch of vinegar, and chilli. Toss on high heat until everything is hot and the vinegar smell lifts.",
      "Taste. Cheap noodles need that vinegar; without it they taste like the packet and the kettle.",
    ],
    "Vinegar wakes up cheap noodles.",
  ),
  r(
    "Stuffed leftover roti",
    10,
    "₹15",
    1,
    ["rotis", "sabzi or cheese", "onion"],
    [
      "Warm the rotis so they fold. Put leftover sabzi or a slice of cheese and chopped onion on one half.",
      "Fold into a semicircle or a roll. Press the edge.",
      "Toast on a medium tawa with a drop of oil until both sides are crisp and the filling is hot.",
      "This is dinner from lunch. There is no shame in it. There is shame in ordering a third time this week.",
    ],
    "Dinner from lunch without the shame.",
  ),
  r(
    "Chicken pepper dry",
    25,
    "₹65",
    2,
    ["250 g chicken", "pepper, garlic, oil"],
    [
      "Cut the chicken into small pieces. Crush plenty of pepper and a few garlic cloves. Toss the chicken with pepper, garlic, salt, and a spoon of oil. Leave it ten minutes while you wash the cooker.",
      "Put the chicken in the cooker with two spoons of water. Two whistles on medium. Release the pressure.",
      "Tip the chicken and its juices onto a hot tawa. Fry until the liquid dries and the pieces take on a dark pepper crust.",
      "Eat one plate with rice or roti. Cool the second plate and refrigerate. Tomorrow it is lunch and you already paid for it.",
    ],
    "Second plate tomorrow with rice.",
  ),
  r(
    "Simple fish fry",
    20,
    "₹60",
    1,
    ["1 slice fish", "chilli, turmeric, salt", "oil"],
    [
      "Buy a slice from the evening market, not the expensive tray under lights. Ask them to clean it if you do not want the sink to smell all night.",
      "Pat the fish very dry. Rub chilli, turmeric, and salt on both sides. Rest five minutes.",
      "Heat a thin layer of oil in a tawa on medium-high. Lay the fish in and do not move it for three minutes. Flip and cook the other side three minutes more. The crust should release from the pan when it is ready.",
      "Drain on paper. Eat with rice and a squeeze of lemon, or with sliced onion. Wash the tawa at once.",
    ],
    "Buy from the evening market, not the fancy tray.",
  ),
  r(
    "Oats vegetable dinner",
    12,
    "₹18",
    1,
    ["1/2 cup oats", "onion, carrot, peas", "pepper"],
    [
      "This is not breakfast. Use water, not milk. Heat oil, fry chopped onion, then carrot and peas, until the onion is soft.",
      "Add the oats, salt, and about a cup of water. Stir as it thickens, three to four minutes, until the oats are soft and savoury.",
      "Finish with a lot of pepper. Taste. If it is gluey, add a splash of water; if it is thin, cook one more minute.",
      "Eat from a bowl. Do not tell the morning oats about this. They would not understand.",
    ],
    "Do not tell breakfast. This is dinner now.",
  ),
  r(
    "Grilled sandwich dinner",
    12,
    "₹30",
    1,
    ["bread", "onion, tomato, cheese or leftover sabzi"],
    [
      "Butter the outer faces of two bread slices. Pile the inside with onion, tomato, and cheese or leftover sabzi. Press closed.",
      "Set a tawa on low-medium. A slow toast melts the middle before the bread burns. Press with a spatula or a smaller lid.",
      "Cook three to four minutes a side until both faces are deep gold and the filling is hot.",
      "Cut a diagonal. Morale matters at 9 p.m. Eat with ketchup or chutney.",
    ],
    "Cut a diagonal. Morale matters.",
  ),
  r(
    "Mix dal night bowl",
    30,
    "₹20",
    2,
    ["handful of any dals mixed", "garlic tadka", "rice or roti"],
    [
      "Empty the last handfuls of whatever dals are left into one bowl. Wash them. This is how you finish jars before weevils do.",
      "Cooker the mix with turmeric and plenty of water, four whistles if there is chana or toor in there, three if it is mostly moong and masoor.",
      "Mash, add salt, and thin to a bowl consistency. Temper garlic in ghee until gold and pour over.",
      "Eat with rice or roti. Tomorrow's lunch is the other half. Label nothing; you will remember it is dal.",
    ],
    "Empty the dal jars before they get weevils.",
  ),
  r(
    "Lauki stew",
    25,
    "₹15",
    1,
    ["lauki", "moong dal handful", "ginger"],
    [
      "Peel and cube the lauki after tasting a scrap for bitterness. Add a handful of washed moong dal, grated ginger, turmeric, and water.",
      "Cooker three whistles, or simmer until both are soft. Mash a few pieces so the pot is a stew, not cubes floating in water.",
      "Add salt and a lot of pepper. A garlic tadka helps if the bowl tastes too clean.",
      "Eat with rice. Bland is a seasoning problem. The vegetable was never the villain.",
    ],
    "Bland is a seasoning problem, not a vegetable problem.",
  ),
  r(
    "Egg pepper roast",
    12,
    "₹25",
    1,
    ["2 boiled eggs", "onion, pepper, chilli"],
    [
      "Boil, cool, and peel two eggs. Leave them whole.",
      "Fry a lot of sliced onion in oil until it is brown and sweet. Add crushed pepper, chilli, and salt.",
      "Add the eggs and roll them in the pan until the whites pick up brown speckles and the onion clings, three to four minutes.",
      "Eat with rice, or eat just the eggs and onion if you are too tired for a second pan. That is still dinner.",
    ],
    "Rice, or just the eggs if you are tired.",
  ),
  r(
    "Spinach dal rice bowl",
    25,
    "₹20",
    1,
    ["dal", "palak", "rice"],
    [
      "If you must use one cooker: put washed dal and rice in the bottom with water, and a bowl of chopped palak on the separator. Three whistles.",
      "If you have two vessels, cook dal and rice as usual and wilt the palak in the dal for the last five minutes.",
      "Mix dal, rice, and palak in a bowl, or keep them in layers. Add salt and a garlic tadka if you did not already.",
      "The green is what makes you feel like an adult. The dal is what makes you full.",
    ],
    "Green makes you feel like an adult.",
  ),
  r(
    "Ghee tadka khichdi dinner",
    25,
    "₹18",
    1,
    ["rice + moong", "ghee, jeera, chilli"],
    [
      "Wash equal-ish parts rice and moong dal. Cooker with turmeric, salt, and extra water so the result is softer than the lunch khichdi — a spoon should sink.",
      "Three whistles, natural release. Stir in a spoon of ghee if it looks dry.",
      "Make a tadka of more ghee than lunch allowed, jeera, and a dried chilli. Pour it over. The surface should shine.",
      "Eat from a bowl, slowly. This is the correct last meal of a long day. Do not improve it with ambition.",
    ],
    "The correct last meal of a long day.",
  ),
  r(
    "Onion tomato curry and rice",
    20,
    "₹12",
    1,
    ["2 onions", "2 tomatoes", "chilli, turmeric"],
    [
      "Slice the onions. Chop the tomatoes. This is the dinner for when the fridge is a bottle of chilli and a half onion you forgot.",
      "Heat oil and cook the onions on medium until they are soft and starting to brown, a full eight minutes. Do not rush this; the sweetness is the curry.",
      "Add tomato, turmeric, chilli, and salt. Cook until the mix turns glossy and the oil returns to the edges, another eight minutes. Add a splash of water if it sticks.",
      "Pour it over hot rice. Taste. If it is sharp, a pinch of sugar; if it is flat, more salt. You cooked a curry from condiments. That is the skill.",
    ],
    "When the fridge is a condiment shelf.",
  ),
];

module.exports = { BREAKFAST, LUNCH, SNACKS, DINNER };
